# Generated by Django 6.1 on 2026-09-23 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_starred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Univcourses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('choice', 'CHOICE')], default='1', max_length=10)),
                ('category', models.CharField(choices=[('datascience', 'DataScience'), ('cybersecurity', 'CyberSecurity'), ('business', 'Business'), ('moral', 'Moral')], default='business', max_length=255)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
